#' Search NBS for a given ID
#'
#' Starting from the NBS home screen, select the correct type of event and
#' search by event ID.
#'
#' @param ID_value Value to search for
#' @param ID_type Event ID type to select from dropdown
#' @return Nothing
#' @export
nbs_search <- function(ID_value, ID_type = "Investigation ID") {
  remDr$findElements("name", "ESR100_textbox")[[1]]$sendKeysToElement(list(ID_type, key = "tab"))
  remDr$findElements("name", "patientSearchVO.actId")[[1]]$sendKeysToElement(list(ID_value))
  remDr$executeScript("searchPatient();")
  remDr$findElements("id", "searchResultsTable")[[1]]$findChildElements("tag name", "a")[[7]]$clickElement()
}

#' Load NBS home screen
#'
#' Navigate to the NBS login page, enter username and password
#' , and enter the specified environment (defaults to production)
#'
#' @param u NBS Username
#' @param p NBS Password
#' @param environment Environment to enter
#' @param url url for NBS login page (e.g., 'https://hssi.tn.gov/auth/login')
#' @return Nothing
#' @export
nbs_load <- function(u = "", p = "", environment = "NBS Production", url = "https://hssi.tn.gov/auth/login") {
  remDr$navigate(url)
  remDr$findElement(using = "name", value = "usr_name")$clearElement()
  remDr$findElement(using = "name", value = "usr_name")$sendKeysToElement(list(u))
  remDr$findElement(using = "name", value = "usr_password")$clearElement()
  remDr$findElement(using = "name", value = "usr_password")$sendKeysToElement(list(p))
  remDr$findElements("tag name", "button")[[2]]$clickElement()
  if (remDr$getTitle() == "HSSI Welcome") {
    remDr$findElements("class", "btn")[[1]]$clickElement()
  }
  Sys.sleep(.5)
  remDr$findElements("link text", environment)[[1]]$clickElement()
}

#' Download a file from NBS
#'
#' Download documents accessed through links in NBS (e.g., attachments).
#'
#' @param element HTML element for file
#' @param outputname Desired name for downloaded file without extension
#' @param url Base url for NBS instance
#' (e.g., 'https://nbsproduction.tn.gov/nbs/')
#' @return T/F if file downloaded
#' @export
nbs_download_file <- function(element, outputname, url = "https://nbsproduction.tn.gov/nbs/") {
  old.exact.name <- tryCatch(unlist(element$getElementText()), error = function(e) {
    return(NA)
  })
  filetype <- tools::file_ext(old.exact.name)
  new.name <- paste0(outputname, ".", filetype)
  if (!is.na(old.exact.name)) {
    attachment.exists <- T
    old.url <- unlist(element$getElementAttribute("href"))
    attachment.uid <- substr(old.url, str_locate(old.url, "AttachmentUid=")[2] + 1, stringr::str_locate(old.url, "fileNmTxt")[1] - 2)
    remDr$navigate(paste0(url, "InvDownloadFile.do?ContextAction=doDownload&nbsAttachmentUid=", attachment.uid, "&fileNmTxt=", new.name))
  } else {
    (attachment.exists <- F)
  }
  return(attachment.exists)
}


#' Filter queue dropdown
#'
#' Open a queue's dropdown filter and select specified elements.
#' When grepl = T, many results may be selected using regex pattern matching.
#' When select_all = T, the 'Select all' option is clicked, which reverses the
#' selection
#'
#' @param dropdown Number representing which dropdown to use (1 is far left)
#' @param search_for Pattern to match in dropdown options
#' @param grepl T/F whether to match multiple options by regex pattern, or
#' match one option exactly
#' @param select_all T/F whether to uncheck select all prior to matching
#' @return None
#' @export
nbs_queue_filter <- function(dropdown, search_for, grepl = F, select_all = F) {
  remDr$findElements("id", "queueIcon")[[dropdown]]$clickElement()
  options <- remDr$findElements("class", "sortable")[[dropdown]]$findChildElements("class", "pText")
  if (select_all) {
    remDr$findElements("class", "sortable")[[dropdown]]$findChildElement("class", "selectAll")$clickElement()
  }
  for (r in 1:length(options)) {
    if (!grepl) {
      if (unlist(options[[r]]$getElementText()) == search_for) {
        options[[r]]$clickElement()
        break
      }
    } else {
      if (grepl(search_for, unlist(options[[r]]$getElementText()), ignore.case = T)) {
        options[[r]]$clickElement()
      }
    }
  }
  remDr$executeScript("selectfilterCriteria();")
}

#' Print the current page as a pdf
#'
#' Prints the current NBS page as a pdf. The pdf is initially saved in the
#'  default download directory (which must be specified in
#'  chrome_open_browser()).
#'  The pdf is then renamed and possibly moved to a different folder.
#'  The default printing method pdf is not exactly equivalent to the pdf
#'  generated by using the 'Print'
#'  button in NBS, but performance is improved. Setting legacy_print to TRUE
#'  will use aspects of the NBS print button, but this method is slower and
#'  more error prone and should only be used when needed
#'  (e.g., better formatting for printing legacy cases)
#'
#' @param pdfname Desired name for the pdf.
#' @param folder (Optional) Folder location for the pdf after download. Usually
#' unnecessary since pdf will download in the location specified in 'print_to'
#' parameter of chrome_open_browser().
#' @param legacy_print Print using the NBS print button. Better quality for
#' legacy pages, but sometimes causes errors and is slower.
#'
#' @return None
#' @export
nbs_print_pdf <- function(pdfname, folder = NA, legacy_print = F) {
  download_location <- remDr$extraCapabilities$chromeOptions$prefs$savefile.default_directory
  if (is.null(download_location)) {
    message("ERROR: No download directory set. Set print_to argument in chrome_open_browser()")
  } else {

    if (legacy_print) {
      home.window <- remDr$getCurrentWindowHandle()[[1]]
      remDr$findElement("name", "Print")$clickElement()
      Sys.sleep(.2)
      all.window <- remDr$getWindowHandles()
      preview.Window <- all.window[!all.window %in% home.window][[1]]
      chrome_window_switch(preview.Window)
      Sys.sleep(.2)
    }

    page.name <- unlist(remDr$getTitle())
    if (page.name == "") page.name <- stringr::str_extract(remDr$getCurrentUrl(),"Load.*\\.do")

    old.name <- paste0(download_location, "\\", page.name, ".pdf")
    if (!is.na(folder)) {
      if (!grepl("[\\|/]$", folder)) folder <- paste0(folder, "/")
      pdfname <- paste0(folder, pdfname)
    } else {
      pdfname <- paste0(download_location, "/", pdfname)
    }


    if (file.exists(old.name)) {
      file.remove(old.name)
    }
    Sys.sleep(1)
    remDr$executeScript("window.print();")

    transferred <- F
    for (w in 1:60) {
      if (file.exists(old.name)) {
        file.rename(old.name, pdfname)
        transferred <- T
        break
      } else {
        Sys.sleep(1)
      }
    }


    if (legacy_print) {
      Sys.sleep(.2)
      remDr$closeWindow()
      Sys.sleep(.2)
      chrome_window_switch(home.window)
    }

    return(transferred)
  }
}

#' Mark an event as reviewed
#'
#' @return "Marked as Reviewed" or "Already marked"
#' @export
nbs_mark_as_reviewed<-function(){
  if('markReviewd' %in% html_attr(html_nodes(read_html(remDr$getPageSource()[[1]]),'input'),'name')){
    remDr$findElement('name','markReviewd')$clickElement()
    return('Marked as Reviewed')
  }else{
    return('Already marked')
  }
}


#' Determine if the current page is a legacy page
#'
#' @return T/F
#' @export
nbs_is_legacy_page <- function() {
  length(rvest::html_node(rvest::read_html(remDr$getPageSource()[[1]]), '.cellColor'))!=2
  }
