
#' Navigate to a queue
#'
#' Navigate to a queue
#'
#' @param queue Name of the queue to load
#' @return Nothing
#' @export
nbs_queue_load<-function(queue){
  if(remDr$getTitle()!="NBS Dashboard"){nbs_home_page()}
  check_in('Queue',queue)
  remDr$findElement('partial link text',queue)$clickElement()
}


#' Get size of current queue
#'
#' Get size of current queue
#'
#' @return Size of current queue
#' @export
nbs_queue_size<-function(){
  as.numeric(remDr$findElement('id','queueCnt')$getElementAttribute('value'))
}

#' Filter queue
#'
#' Open a queue's dropdown filter and select specified elements.
#' When grepl = T, many results may be selected using regex pattern matching.
#' When select_all = T, the 'Select all' option is clicked, which reverses the
#' selection. If the dropdown is a text match, grepl and select_all are ignored.
#'
#' @param dropdown Number representing which dropdown to use (1 is far left)
#' @param search_for Pattern to match in dropdown options
#' @param grepl T/F whether to match multiple options by regex pattern, or
#' match one option exactly
#' @param select_all T/F whether to uncheck select all prior to matching
#' @return None
#' @export
nbs_queue_filter <- function(dropdown, search_for, grepl = F, select_all = F) {
  ps<-remDr$getPageSource() %>%
    unlist() %>%
    read_html()
  
  if(is.numeric(dropdown)){
    
  }else{
    filter_names<-ps %>% html_elements('.sortable') %>% html_elements('a') %>% html_text()
    dropdown<-which(filter_names==dropdown)
  }
  
  if(length(dropdown)!=1){
    message('Filter not found')
    return(NA)
  }
  
  hps<-ps %>% html_elements('.sortable') %>% .[dropdown]
  
  hclass<- hps %>%
    html_elements('div') %>% html_attr('class')
  
  if('multiTextOptions' %in% hclass){
    queue_contains(dropdown,search_for,ps)
  }else{
    
    remDr$findElements("id", "queueIcon")[[dropdown]]$clickElement()
    options <- remDr$findElements("class", "sortable")[[dropdown]]$findChildElements("class", "pText")
    option_text<-hps %>% html_elements('.pText') %>% html_text()
    if (select_all) {
      remDr$findElements("class", "sortable")[[dropdown]]$findChildElement("class", "selectAll")$clickElement()
    }
    for (r in 1:length(options)) {
      if (!grepl) {
        if (option_text[r]== search_for) {
          options[[r]]$clickElement()
          break
        }
      } else {
        if (grepl(search_for, option_text[r], ignore.case = T)) {
          options[[r]]$clickElement()
        }
      }
    }
    remDr$executeScript("selectfilterCriteria();")
  }
}

#' Filter queue dropdown from supervisor queue
#'
#' Open a queue's dropdown filter and select specified elements.
#' When grepl = T, many results may be selected using regex pattern matching.
#' When select_all = T, the 'Select all' option is clicked, which reverses the
#' selection. If you are attempting to select 1 or more options, 
#' but no options are actually in the dropdown list, 
#' all options will remain selected and be included in the shown results.
#' To prevent this, an error is generated by default if no option is selected.
#'
#' @param dropdown Number representing which dropdown to use (1 is far left)
#' @param search_for Pattern to match in dropdown options
#' @param grepl T/F whether to match multiple options by regex pattern, or
#' match one option exactly
#' @param select_all T/F whether to uncheck select all prior to matching
#' @param noclick_error T/F Should an error be generated when no option is clicked (aside from select all). Defaults to the opposite of select_all.
#' @return None
#' @export
nbs_queue_filter_supervisor<-function (dropdown, search_for, grepl = F, select_all = F, noclick_error=!select_all) {
  dd <- remDr$findElements("class", "multiSelect")[[dropdown]]
  dd_id <- gsub("ig", "", unlist(dd$getElementAttribute("id")))
  dd$clickElement()
  option_names <- unlist(str_split(remDr$findElement("id", 
                                                     dd_id)$getElementText(), "\n "))
  options <- remDr$findElement("id", dd_id)$findChildElements("tag name", 
                                                              "input")
  clicked_once<-F
  if (select_all) {
    options[[1]]$clickElement()
  }
  for (r in 2:length(options)) {
    if (!grepl) {
      if (option_names[r] == search_for) {
        options[[r]]$clickElement()
        clicked_once<-T
        break
      }
    }
    else {
      if (grepl(search_for, option_names[r], ignore.case = T)) {
        options[[r]]$clickElement()
        clicked_once<-T
      }
    }
  }
  if(!clicked_once & noclick_error){
    stop('Failed to select any dropdown options')
  }
  remDr$executeScript("selectfilterCriteria();")
}

#' Filters queue columns that use a contains string search
#'
#' Filters queue columns that use a contains string search
#'
#' @param dropdown Number representing which dropdown to use (1 is far left)
#' @param search_for Pattern to match in dropdown options
#' 
#' @return None
queue_contains<-function(dropdown,search_for,pagesource){
  dropdowns<-pagesource %>%
    html_nodes('#queueIcon')
  
  axpath<-find_ancestor_xpath(dropdowns[dropdown],'class','sortable')
  axsub <- as.numeric(str_extract(str_extract(axpath,"table\\[\\d\\]" ),'\\d'))
  naxsub<-paste0('table[',axsub-1,']')
  axpath <- gsub(paste0("table\\[",axsub,"\\]"), naxsub, axpath)
  remDr$findElements("id", "queueIcon")[[dropdown]]$clickElement()
  remDr$findElement('xpath',axpath )$findChildElements('tag name','input')[[3]]$sendKeysToElement(list(search_for))
  remDr$executeScript("selectfilterCriteria();")
}

#' Select a link or checkbox in a queue
#'
#' Select a link or checkbox in a queue
#'
#' @param row Row to select
#' @param column Column to select (includes checkbox column)
#' 
#' @return None
#' @export
nbs_queue_row_click<-function(row=1, col=1){
  
  if(row%%2==0){
    row_class<-'even'
    row<-row/2
  }else{
    row_class<-'odd'
    row<-row/2+1
  }
  
  cur_element<-remDr$getPageSource() %>% unlist() %>% read_html() %>% 
    html_elements(paste0('.',row_class)) %>% 
    .[row] %>% 
    html_children() %>% 
    .[col] %>% html_children()
  cur_el_attr<-unlist(html_attrs(cur_element))
  if('checkbox' %in% cur_el_attr | '#' %in% cur_el_attr) {
    epath<-xml_path(cur_element)[1]
    table_num<-stringr::str_extract(epath,'table\\[\\d+\\]')
    table_num_1<-as.numeric(stringr::str_extract(table_num,'\\d+'))
    nepath<-gsub(paste0('table\\[',table_num_1,'\\]'),paste0('table[',table_num_1-1,']'),epath)
    remDr$findElement('xpath',nepath)$clickElement()  }else{
    message('Nothing to click')
  }
}

#' Get information from a queue row
#'
#' Get information from a queue row
#'
#' @param row Row to select
#' 
#' @return Named character vector of row data
#' @export
nbs_queue_row_info<-function(row=1){
  if(row%%2==0){
    row_class<-'even'
    row<-row/2
  }else{
    row_class<-'odd'
    row<-row/2+1
  }
  cnames<-remDr$findElements('class','sortable')
  cnames<-unlist(sapply(cnames, function(x) x$getElementText()))
  rdata<-unlist(lapply(remDr$findElements('class',row_class)[[row]]$findChildElements('tag name','td'), function(x) x$getElementText()))
  names(rdata)<-c('checkbox',cnames)
  rdata
}


#' Return to a queue
#'
#' Return to a queue
#' 
#' @return None
#' @export
nbs_queue_return<-function(){
  check_in('Queue return')
  remDr$findElement('partial link text','Return to')$clickElement()
}

