
#' Search for a patient by ID
#' 
#' This function searches for a patient from the home page.
#' 
#' @param id The patient ID
#'  
#' @return NULL
#' @export
nbs_patient_search<-function(id){
  remDr$findElement('id','DEM229')$sendKeysToElement(list(as.character(id)))
  remDr$executeScript('searchPatient();')
  remDr$findElement('xpath','//*[@id="searchResultsTable"]/tbody/tr/td[1]/a')$clickElement()
}

#' Search NBS for a given ID
#'
#' Starting from the NBS home screen, select the correct type of event and
#' search by event ID.
#'
#' @param ID_value Value to search for
#' @param ID_type Event ID type to select from dropdown
#' @return Nothing
#' @export
nbs_search <- function(ID_value, ID_type = "Investigation ID") {
  remDr$findElements("name", "ESR100_textbox")[[1]]$sendKeysToElement(list(ID_type, key = "tab"))
  remDr$findElements("name", "patientSearchVO.actId")[[1]]$sendKeysToElement(list(ID_value))
  remDr$executeScript("searchPatient();")
  remDr$findElements("id", "searchResultsTable")[[1]]$findChildElements("tag name", "a")[[7]]$clickElement()
}



#' Download a file from NBS
#'
#' Download documents accessed through links in NBS - e.g., attachments.
#'
#' @param element HTML element for file
#' @param outputname Desired name for downloaded file without extension
#' @param url Base url for NBS instance - e.g., 'https://nbsproduction.tn.gov/nbs/'
#' @return T/F if file downloaded
#' @export
nbs_file_download <- function(element, outputname, url = "https://nbsproduction.tn.gov/nbs/") {
  old.exact.name <- tryCatch(unlist(element$getElementText()), error = function(e) {
    return(NA)
  })
  filetype <- tools::file_ext(old.exact.name)
  new.name <- paste0(outputname, ".", filetype)
  if (!is.na(old.exact.name)) {
    attachment.exists <- T
    old.url <- unlist(element$getElementAttribute("href"))
    attachment.uid <- substr(old.url, str_locate(old.url, "AttachmentUid=")[2] + 1, stringr::str_locate(old.url, "fileNmTxt")[1] - 2)
    remDr$navigate(paste0(url, "InvDownloadFile.do?ContextAction=doDownload&nbsAttachmentUid=", attachment.uid, "&fileNmTxt=", new.name))
  } else {
    (attachment.exists <- F)
  }
  return(attachment.exists)
}




#' Print the current page as a pdf
#'
#' Prints the current NBS page as a pdf. The pdf is initially saved in the
#'  default download directory (which must be specified in
#'  chrome_open_browser()).
#'  The pdf is then renamed and possibly moved to a different folder.
#'  The default printing method pdf is not exactly equivalent to the pdf
#'  generated by using the 'Print'
#'  button in NBS, but performance is improved. Setting legacy_print to TRUE
#'  will use aspects of the NBS print button, but this method is slower and
#'  more error prone and should only be used when needed
#'  (e.g., better formatting for printing legacy cases)
#'
#' @param pdfname Desired name for the pdf.
#' @param folder (Optional) Folder location for the pdf after download. Usually
#' unnecessary since pdf will download in the location specified in 'print_to'
#' parameter of chrome_open_browser().
#' @param legacy_print Print using the NBS print button. Better quality for
#' legacy pages, but sometimes causes errors and is slower.
#'
#' @return None
#' @export
nbs_pdf_print <- function(pdfname, folder = NA, legacy_print = F) {
  download_location <- remDr$extraCapabilities$chromeOptions$prefs$savefile.default_directory
  if (is.null(download_location)) {
    message("ERROR: No download directory set. Set print_to parameter.")
  } else {

    if (legacy_print) {
      home.window <- remDr$getCurrentWindowHandle()[[1]]
      remDr$findElement("name", "Print")$clickElement()
      Sys.sleep(.2)
      all.window <- remDr$getWindowHandles()
      preview.Window <- all.window[!all.window %in% home.window][[1]]
      chrome_window_switch(preview.Window)
      Sys.sleep(.2)
    }

    page.name <- unlist(remDr$getTitle())
    if (page.name == "") page.name <- stringr::str_extract(remDr$getCurrentUrl(),"Load.*\\.do")

    old.name <- paste0(download_location, "\\", page.name, ".pdf")
    if (!is.na(folder)) {
      if (!grepl("[\\|/]$", folder)) folder <- paste0(folder, "/")
      pdfname <- paste0(folder, pdfname)
    } else {
      pdfname <- paste0(download_location, "/", pdfname)
    }


    if (file.exists(old.name)) {
      file.remove(old.name)
    }
    Sys.sleep(1)
    remDr$executeScript("window.print();")

    transferred <- F
    for (w in 1:60) {
      if (file.exists(old.name)) {
        file.rename(old.name, pdfname)
        transferred <- T
        break
      } else {
        Sys.sleep(1)
      }
    }


    if (legacy_print) {
      Sys.sleep(.2)
      remDr$closeWindow()
      Sys.sleep(.2)
      chrome_window_switch(home.window)
    }

    return(transferred)
  }
}

#' Mark an event as reviewed
#'
#' @return "Marked as Reviewed" or "Already marked"
#' @export
nbs_lab_mark_as_reviewed<-function(){
  if('markReviewd' %in% html_attr(html_nodes(read_html(remDr$getPageSource()[[1]]),'input'),'name')){
    remDr$findElement('name','markReviewd')$clickElement()
    return('Marked as Reviewed')
  }else{
    return('Already marked')
  }
}


#' Determine if the current page is a legacy page
#'
#' @return T/F
#' @export
nbs_page_is_legacy <- function() {
  length(rvest::html_node(rvest::read_html(remDr$getPageSource()[[1]]), '.cellColor'))!=2
}


#' Go to the NBS home page
#'
#' @param check_legacy T/F. If TRUE, checks if the page is legacy before clicking the home button, since legacy pages need slightly different code.
#'
#' @return Nothing
#' @export
nbs_home_page<-function(check_legacy=F){
  pclass<- "navLink"
  if(check_legacy){
    if(nbs_page_is_legacy()){
      pclass<-'navBar'
    }
  }
  remDr$findElements("class", pclass)[[1]]$clickElement()
}




#' Go to and export an NBS report
#' 
#' This function will find an NBS report by name, then enter basic filters and column selections before exporting the report results.
#' Will first attempt to load the home page if not already there.
#' Advanced filtering not added yet, but possible.
#' 
#' @param report String. The name of the report.
#' @param basic Named list. Values to enter/select in the basic filtering page, named by their HTML ID. 
#' To click an element, use 'elementID'=NA. 
#' To enter text, use 'elementID'='text_to_enter'. 
#' To select from a dropdown, use 'elementID'=c('option1','option2'). To select just one dropdown option, you will need to provide a vector of options with a length greater than 1, so provide an additional fake option (will generate a message), or list the same option 3 times (first 2 cancel out).
#' @param columns NA/character or numeric vector. If NA, will export all columns. Otherwise, will export the columns named or specified via index.
#'  
#' @return NULL
#' @export
nbs_report<-function(report
                     , basic=list('id_T_T01a'=Sys.Date()-30, 'id_T_T01b'=Sys.Date())
                     , columns=NA
){

    ct<-unlist(remDr$getCurrentUrl())
    if(grepl('managereports',ct, ignore.case = T)){
      
    }else if(grepl('nbs/report/',ct, ignore.case = T)){
      remDr$findElement('id','id_cancel_top_ToolbarButtonGraphic')$clickElement()
    } else {
      nbs_home_page()
      remDr$navigate('https://nbsproduction.tn.gov/nbs/ManageReports.do')
      remDr$executeScript('hideBackButtonMessage()')
    }

  
  
  # Find all dropdowns
  dropdown_boxes<-remDr$findElements('tag name','img')
  # If they are closed, open them
  for (db in dropdown_boxes){
    if(grepl('plus',db$getElementAttribute('src'))) db$clickElement()
  }
  
  ps<-remDr$getPageSource() %>% unlist() %>% rvest::read_html()
  
  tab_num<-ps %>%  html_elements(xpath='//*[@id="frm"]/table[2]/tbody/tr[2]/td/table/tbody/tr[3]/td/table[5]/tbody/tr[2]/td/table/tbody/tr/td') %>% 
    length()
  
  
  dtext<- ps %>%
    rvest::html_elements('.hoverDescLink') %>% 
    rvest::html_text() %>% 
    tolower() %>% trimws()
  
  rfound<-which(tolower(report)==dtext)
  
  if(length(rfound)==0){
    message('Report not found; check for typos')
    return(NULL)
  }
  
  if(length(rfound)>1) message('Multiple reports matched, choosing first')
  
  remDr$findElements('link text','Run')[[rfound[1]]]$clickElement()
  
  ps<-remDr$getPageSource() %>% unlist() %>% rvest::read_html()
  
  tab_num<-ps %>%  html_elements(xpath='//*[@id="frm"]/table[2]/tbody/tr[2]/td/table/tbody/tr[3]/td/table[5]/tbody/tr[2]/td/table/tbody/tr/td') %>% 
    length()
  
  if(length(basic)>0){
  for(b in 1:length(basic)){
    if(any(is.na(basic[[b]]))){
      remDr$findElement('id',names(basic[b]))$clickElement()
      next
    }
    
    if(length(basic[[b]])>1){
      bb<-tolower(basic[[b]])
      
      
      
      dlist<-ps %>%
        rvest::html_nodes(xpath=paste0('//*[@id="',names(basic[b]),'"]')) %>% 
        rvest::html_nodes('option') 
      dtext<-dlist %>% rvest::html_text() %>% tolower()
      
      for (sb in bb){
        copt<-which(sb==dtext)
        
        if(length(copt)==0){
          message(paste0("Can't find option ",sb))
          next
        }else{
          remDr$findElement('xpath',paste0('//*[@id="',names(basic[b]),'"]/option[',copt[1],']'))$clickElement()
        }
        
      }
      next
    }
    
    if('Date' %in% class(basic[[b]])){
      basic[[b]]<-TNTools::tn_clean_date(basic[[b]],'%m%d%Y')
    }
    
    remDr$findElement('id',names(basic[b]))$sendKeysToElement(list("\uE009a\uE009",basic[[b]]))
  }
  }
  
  if(tab_num>2){
  remDr$findElement('xpath','//*[@id="frm"]/table[2]/tbody/tr[2]/td/table/tbody/tr[3]/td/table[5]/tbody/tr[2]/td/table/tbody/tr/td[3]/table/tbody/tr/td/table/tbody/tr/td[2]/a')$clickElement()
  
  if(any(is.na(columns))){
    remDr$findElement('id','id_AddAll')$clickElement()
  }else if(length(columns==1)&any(columns=='')){
    
    }else{
    option_list<-remDr$findElement('id','id_AVAILABLE_COLUMNS_list')
    col_options<-option_list$getElementText()
    
    option_list_selections<-option_list$findChildElements('tag name','option')
    
    col_options<-unlist(stringr::str_split(col_options,'\n'))
    
    if('integer' %in% class(columns)){
      col_selected<-col_options[columns]
    }else{
      col_selected<-columns
    }
    
    for (cl in col_selected){
      cindex<-(1:length(col_options))[cl==col_options]
      option_list_selections[[cindex]]$clickElement()
    }
    
    remDr$findElement('id','id_Add')$clickElement()
  }
  }
  # Hit export button
  remDr$findElement('id','id_export_top_ToolbarButtonGraphic')$clickElement()
  
}

