#' Get the base NBS url for a page
#' 
#' Used to accommodate various deployments of NBS
#'  
#' @return String. Base url
#' @export
nbs_url_get<-function(){
  nbs_url<-remDr$getCurrentUrl() %>% 
    unlist() %>% 
    stringr::str_replace('/nbs/.*','/nbs/')
  return(nbs_url)
}

#' Search for a patient by ID
#' 
#' This function searches for a patient from the home page.
#' 
#' @param id The patient ID
#'  
#' @return NULL
#' @export
nbs_patient_search<-function(id){
  remDr$findElement('id','DEM229')$sendKeysToElement(list(as.character(id)))
  remDr$executeScript('searchPatient();')
  remDr$findElement('xpath','//*[@id="searchResultsTable"]/tbody/tr/td[1]/a')$clickElement()
}

#' Search NBS for a given ID
#'
#' Starting from the NBS home screen, select the correct type of event and
#' search by event ID.
#'
#' @param ID_value Value to search for
#' @param ID_type Event ID type to select from dropdown
#' @param verbose T/F. Should a message be generated upon unsuccessful search?
#' @return Nothing
#' @export

nbs_search <- function(ID_value, ID_type = "Investigation ID", verbose=T) {
  remDr$findElements("name", "ESR100_textbox")[[1]]$sendKeysToElement(list(ID_type, key = "tab"))
  remDr$findElements("name", "patientSearchVO.actId")[[1]]$sendKeysToElement(list(ID_value))
  remDr$executeScript("searchPatient();")
  
  if(grepl('resulted in 0 ',remDr$findElement('xpath','//*[@id="bd"]/div[3]')$getElementText()[[1]])){
    if(verbose) message('Search resulted in no matches')
    return(F)
  }
  
  remDr$findElements("id", "searchResultsTable")[[1]]$findChildElements("tag name", "a")[[7]]$clickElement()
  return(T)
}



#' Download a file from NBS
#'
#' Download documents accessed through links in NBS - e.g., attachments.
#'
#' @param element HTML element for file
#' @param outputname Desired name for downloaded file without extension
#' @return T/F if file downloaded
#' @export
nbs_file_download <- function(element, outputname) {
  old.exact.name <- tryCatch(unlist(element$getElementText()), error = function(e) {
    return(NA)
  })
  filetype <- tools::file_ext(old.exact.name)
  new.name <- paste0(outputname, ".", filetype)
  if (!is.na(old.exact.name)) {
    attachment.exists <- T
    old.url <- unlist(element$getElementAttribute("href"))
    attachment.uid <- substr(old.url, str_locate(old.url, "AttachmentUid=")[2] + 1, stringr::str_locate(old.url, "fileNmTxt")[1] - 2)
    remDr$navigate(paste0(nbs_url, "InvDownloadFile.do?ContextAction=doDownload&nbsAttachmentUid=", attachment.uid, "&fileNmTxt=", new.name))
  } else {
    (attachment.exists <- F)
  }
  return(attachment.exists)
}




#' Print the current page as a pdf
#'
#' Prints the current NBS page as a pdf. The pdf is initially saved in the
#'  default download directory (which must be specified in
#'  chrome_open_browser()).
#'  The pdf is then renamed and possibly moved to a different folder.
#'  The default printing method pdf is not exactly equivalent to the pdf
#'  generated by using the 'Print'
#'  button in NBS, but performance is improved. Setting legacy_print to TRUE
#'  will use aspects of the NBS print button, but this method is slower and
#'  more error prone and should only be used when needed
#'  (e.g., better formatting for printing legacy cases)
#'
#' @param pdfname Desired name for the pdf.
#' @param folder (Optional) Folder location for the pdf after download. Usually
#' unnecessary since pdf will download in the location specified in 'print_to'
#' parameter of chrome_open_browser().
#' @param legacy_print Print using the NBS print button. Better quality for
#' legacy pages, but sometimes causes errors and is slower.
#'
#' @return None
#' @export
nbs_pdf_print <- function(pdfname, folder = NA, legacy_print = F) {
  download_location <- remDr$extraCapabilities$chromeOptions$prefs$savefile.default_directory
  if (is.null(download_location)) {
    message("ERROR: No download directory set. Set print_to parameter.")
  } else {

    if (legacy_print) {
      home.window <- remDr$getCurrentWindowHandle()[[1]]
      remDr$findElement("name", "Print")$clickElement()
      Sys.sleep(.2)
      all.window <- remDr$getWindowHandles()
      preview.Window <- all.window[!all.window %in% home.window][[1]]
      chrome_window_switch(preview.Window)
      Sys.sleep(.2)
    }

    page.name <- gsub(':','_',unlist(remDr$getTitle()))
    if (page.name == "") page.name <- stringr::str_extract(remDr$getCurrentUrl(),"Load.*\\.do")

    old.name <- paste0(download_location, "\\", page.name, ".pdf")
    if (!is.na(folder)) {
      if (!grepl("[\\|/]$", folder)) folder <- paste0(folder, "/")
      pdfname <- paste0(folder, pdfname)
    } else {
      pdfname <- paste0(download_location, "/", pdfname)
    }


    if (file.exists(old.name)) {
      file.remove(old.name)
    }
    Sys.sleep(1)
    remDr$executeScript("window.print();")

    transferred <- F
    for (w in 1:60) {
      if (file.exists(old.name)) {
        file.rename(old.name, pdfname)
        transferred <- T
        break
      } else {
        Sys.sleep(1)
      }
    }


    if (legacy_print) {
      Sys.sleep(.2)
      remDr$closeWindow()
      Sys.sleep(.2)
      chrome_window_switch(home.window)
    }

    return(transferred)
  }
}




#' Determine if the current page is a legacy page
#'
#' @return T/F
#' @export
nbs_page_is_legacy <- function() {
  length(rvest::html_node(rvest::read_html(remDr$getPageSource()[[1]]), '.cellColor'))!=2
}


#' Go to the NBS home page
#'
#' @param check_legacy T/F. If TRUE, checks if the page is legacy before clicking the home button, since legacy pages need slightly different code.
#'
#' @return Nothing
#' @export
nbs_home_page<-function(check_legacy=F){
  #pclass<- "navLink"
  #if(check_legacy){
  #  if(nbs_page_is_legacy()){
   #   pclass<-'navBar'
  #  }
  #}
  
  #top_bar<-remDr$findElements("class", "navLink")
  #if(length(top_bar)==0){
  #  top_bar<-remDr$findElements("class", 'navBar')
  #}
  #top_bar[[1]]$clickElement()
  
  remDr$navigate(paste0(nbs_url,'HomePage.do?method=loadHomePage'))
}

#' Go to a user management page
#'
#' @param dc_num DC number for user
#' @param type Do you want to 'view' or 'edit' the user?
#'
#' @return Nothing
#' @export
nbs_user_management <-function(dc_num, type='view'){
  remDr$navigate(paste0(nbs_url,'loadUser.do?OperationType=',type,'&userID=',dc_num))
  remDr$executeScript('hideBackButtonMessage()')
  return()
}

#' Set a user as active or inactive
#'
#' @param status Desired user status. Active or Inactive.
#'
#' @return Nothing
#' @export
nbs_user_set_status<-function(status){
  status<-toupper(status)
  remDr$findElement('id',status)$clickElement()
  if(status=='INACTIVE') remDr$acceptAlert()
}

#' Submit edits to a user
#'
#' @return Nothing
#' @export
nbs_user_submit <- function(){
  remDr$findElement('id','Submit')$clickElement()
}


#' Go to and export an NBS report
#' 
#' This function will find an NBS report by name, then enter basic filters and column selections before exporting the report results.
#' Will first attempt to load the home page if not already there.
#' Advanced filtering not added yet, but possible.
#' 
#' @param report String. The name of the report.
#' @param basic Named list. Values to enter/select in the basic filtering page, named by their HTML ID. 
#' To click an element, use 'elementID'=NA. 
#' To enter text, use 'elementID'='text_to_enter'. 
#' To select from a dropdown, use 'elementID'=c('option1','option2'). To select just one dropdown option, you will need to provide a vector of options with a length greater than 1, so provide an additional fake option (will generate a message), or list the same option 3 times (first 2 cancel out).
#' @param columns NA/character or numeric vector. If NA, will export all columns. Otherwise, will export the columns named or specified via index.
#'  
#' @return NULL
#' @export
nbs_report<-function(report
                     , basic=list('id_T_T01a'=Sys.Date()-30, 'id_T_T01b'=Sys.Date())
                     , columns=NA
){

    ct<-unlist(remDr$getCurrentUrl())
    if(grepl('managereports',ct, ignore.case = T)){
      
    }else if(grepl('nbs/report/',ct, ignore.case = T)){
      remDr$findElement('id','id_cancel_top_ToolbarButtonGraphic')$clickElement()
    } else {
      nbs_home_page()
      remDr$navigate(paste0(nbs_url,'ManageReports.do'))
      remDr$executeScript('hideBackButtonMessage()')
    }

  
  
  # Find all dropdowns
  dropdown_boxes<-remDr$findElements('tag name','img')
  # If they are closed, open them
  for (db in dropdown_boxes){
    if(grepl('plus',db$getElementAttribute('src'))) db$clickElement()
  }
  
  ps<-remDr$getPageSource() %>% unlist() %>% rvest::read_html()
  
  tab_num<-ps %>%  html_elements(xpath='//*[@id="frm"]/table[2]/tbody/tr[2]/td/table/tbody/tr[3]/td/table[5]/tbody/tr[2]/td/table/tbody/tr/td') %>% 
    length()
  
  
  dtext<- ps %>%
    rvest::html_elements('.hoverDescLink') %>% 
    rvest::html_text() %>% 
    tolower() %>% trimws()
  
  rfound<-which(tolower(report)==dtext)
  
  if(length(rfound)==0){
    message('Report not found; check for typos')
    return(NULL)
  }
  
  if(length(rfound)>1) message('Multiple reports matched, choosing first')
  
  remDr$findElements('link text','Run')[[rfound[1]]]$clickElement()
  
  ps<-remDr$getPageSource() %>% unlist() %>% rvest::read_html()
  
  tab_num<-ps %>%  html_elements(xpath='//*[@id="frm"]/table[2]/tbody/tr[2]/td/table/tbody/tr[3]/td/table[5]/tbody/tr[2]/td/table/tbody/tr/td') %>% 
    length()
  
  if(length(basic)>0){
  for(b in 1:length(basic)){
    if(any(is.na(basic[[b]]))){
      remDr$findElement('id',names(basic[b]))$clickElement()
      next
    }
    
    if(length(basic[[b]])>1){
      bb<-tolower(basic[[b]])
      
      
      
      dlist<-ps %>%
        rvest::html_nodes(xpath=paste0('//*[@id="',names(basic[b]),'"]')) %>% 
        rvest::html_nodes('option') 
      dtext<-dlist %>% rvest::html_text() %>% tolower()
      
      for (sb in bb){
        copt<-which(sb==dtext)
        
        if(length(copt)==0){
          message(paste0("Can't find option ",sb))
          next
        }else{
          remDr$findElement('xpath',paste0('//*[@id="',names(basic[b]),'"]/option[',copt[1],']'))$clickElement()
        }
        
      }
      next
    }
    
    if('Date' %in% class(basic[[b]])){
      basic[[b]]<-TNTools::tn_clean_date(basic[[b]],'%m%d%Y')
    }
    
    remDr$findElement('id',names(basic[b]))$sendKeysToElement(list("\uE009a\uE009",basic[[b]]))
  }
  }
  
  if(tab_num>2){
  remDr$findElement('xpath','//*[@id="frm"]/table[2]/tbody/tr[2]/td/table/tbody/tr[3]/td/table[5]/tbody/tr[2]/td/table/tbody/tr/td[3]/table/tbody/tr/td/table/tbody/tr/td[2]/a')$clickElement()
  
  if(any(is.na(columns))){
    remDr$findElement('id','id_AddAll')$clickElement()
  }else if(length(columns==1)&any(columns=='')){
    
    }else{
    option_list<-remDr$findElement('id','id_AVAILABLE_COLUMNS_list')
    col_options<-option_list$getElementText()
    
    option_list_selections<-option_list$findChildElements('tag name','option')
    
    col_options<-unlist(stringr::str_split(col_options,'\n'))
    
    if('integer' %in% class(columns)){
      col_selected<-col_options[columns]
    }else{
      col_selected<-columns
    }
    
    for (cl in col_selected){
      cindex<-(1:length(col_options))[cl==col_options]
      option_list_selections[[cindex]]$clickElement()
    }
    
    remDr$findElement('id','id_Add')$clickElement()
  }
  }
  # Hit export button
  remDr$findElement('id','id_export_top_ToolbarButtonGraphic')$clickElement()
  
}


#' Go to the page for an event or person
#' 
#' This function accepts a wide variety of NBS local IDs and determines the correct search function to use based on the ID pattern.
#' 
#' @param ID Local ID
#' @param prefer_morbs T/F. Should morb reports be searched for before lab reports?
#'
#' @return T/F
#' @export
nbs_go_to<-function(ID, prefer_morbs=F){
  if(grepl('^psn',ID, ignore.case=T)){
    ID<-nbs_id_convert(ID)
  }
  
  if(grepl('^CAS',ID, ignore.case = T)){
    nbs_investigation_go_to(ID)
  }else if (grepl('^OBS',ID, ignore.case = T)){
    if(!prefer_morbs){
    if(nbs_lab_go_to(ID, verbose=F)){
      return(T)
    }else{
      nbs_morb_go_to(ID)
    }
    }else{
      if(nbs_morb_go_to(ID, verbose=F)){
        return(T)
      }else{
        nbs_lab_go_to(ID)
      }
    }
  }else if(grepl('^DOC',ID, ignore.case = T)){
    nbs_doc_go_to(ID)
  }else{
    if(remDr$getTitle()!="NBS Dashboard"){nbs_home_page(check_legacy = T)}
    nbs_patient_search(ID)
  }
}

#' Go to an event
#' 
#' @param search_type The type of event to search for. Can be Lab ID, Morbidity Report ID, Document ID, or Investigation ID.
#' @param ID Event ID. Required if this function is called from outside the patient page.
#' @param uid The event uid. Providing a uid may be slightly faster.
#' @param patient_page Boolean. Is the function called from a patient page? By default, if an ID is supplied, the home page search is used. Setting patient_page=T speeds up code where the function is called from the patient page.
#' @param verbose T/F. Should some extra messages be printed?
#'
#' @return T/F
go_to_event<-function(search_type, ID=NA,uid=NA,patient_page=F, verbose=T){
  
  if(search_type=='Lab ID'){
    table_name<-'eventLabReport'
    col<-8
    link_col<-1
    direct_url<-"ViewFile1.do?ContextAction=ObservationLabIDOnSummary&observationUID="
  }else if(search_type=='Morbidity Report ID'){
    table_name<-'eventMorbReport'
    col<-7
    link_col<-1
    direct_url<-"ViewFile1.do?ContextAction=ObservationMorbIDOnEvents&observationUID="
  }else if(search_type=='Document ID'){
    table_name<-'eventCaseReports'
    direct_url<-"ViewFile1.do?ContextAction=DocumentIDOnEvents&nbsDocumentUid="
    col<-7
    link_col<-1
  }else if(search_type=='Investigation ID'){
    table_name<-'eventSumaryInv'
    direct_url<-"ViewFile1.do?ContextAction=InvestigationIDOnEvents&publicHealthCaseUID="
    col<-9
    link_col<-2
  }
  
  ID<-as.character(ID)
  uid<-as.character(uid)
  if(sum(is.na(c(ID,uid)))==2){
    message('Error: ID or uid must be supplied')
    return(NA)
  }
  
  if(patient_page){
    
  }else{
    if(remDr$getTitle()!="NBS Dashboard"){nbs_home_page(check_legacy = T)}
    if(nbs_search(ID, search_type, verbose=verbose)){
      
    }else{
      return(F)
    }
  }
  
  if(is.na(uid)){
    lab_list<-remDr$getPageSource() %>%
      unlist() %>%
      read_html() %>%
      html_element(xpath=paste0('//*[@id="',table_name,'"]/tbody')) 
    lab_table<-html_table(lab_list) 
    lab_index<-str_which(unlist(lab_table[,col]),ID)
    
    url<-remDr$findElement('xpath',paste0('//*[@id="',table_name,'"]/tbody/tr[',lab_index,']/td[',link_col,']/a'))$getElementAttribute('href')
    remDr$navigate(unlist(url))
  }else{
    remDr$navigate(paste0(nbs_url,direct_url,uid))
  }
  remDr$executeScript('hideBackButtonMessage()')
  return(T)
}

#' Select a tab from an investigation, lab, or patient page
#' 
#' This function can be used to select a new (or the same) tab in patient pages and NBS labs and investigations that are pagebuilder pages (i.e., not legacy).
#' Use the number of the tab you wish to select. You can call this function on the view or edit page.
#' 
#' @param tab Number for the tab you wish to click. 1 is farthest left.
#'
#' @return Nothing
#' @export
nbs_tab_select<-function(tab){
  remDr$findElement('id',paste0('tabs0head',tab-1))$clickElement()
}
